### ISSUE TITLE
Feature - Add daily totals

### ISSUE THREAD

**Issue by aaron-osher** [dsi-principles-prog/midterm-aaron-osher#2]
create a feature that will calculate the total number of events per date and outputs a new column with this total for each day.

**Details**
Inputs - treatment_date
Expected output - new column with daily counter, should be numeric

treatment_date is the the day that an event occurred, we want to add up all the events on a given day.

**Testing**
Values should be numeric whole numbers

**Comment by amandashort** [comment]
Closed!
